/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package KindergartenMgtSystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Admin
 */
public class Buses extends javax.swing.JFrame {

    /**
     * Creates new form Buses
     */
    public Buses() {
        initComponents();
        DisplayBuses();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        busPlateTxt = new javax.swing.JTextField();
        driverTxt = new javax.swing.JTextField();
        driverNmbrTxt = new javax.swing.JTextField();
        editBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        HomeBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        busTbl = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Buses");

        jPanel3.setBackground(new java.awt.Color(51, 153, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bus Reg", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(102, 153, 255))); // NOI18N
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setName(""); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Bus Plate");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Driver");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Driver Number");

        busPlateTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busPlateTxtActionPerformed(evt);
            }
        });

        driverNmbrTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                driverNmbrTxtActionPerformed(evt);
            }
        });

        editBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        editBtn.setForeground(new java.awt.Color(102, 153, 255));
        editBtn.setText("Edit");
        editBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editBtnMouseClicked(evt);
            }
        });

        addBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addBtn.setForeground(new java.awt.Color(0, 153, 51));
        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        deleteBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(255, 0, 102));
        deleteBtn.setText("Delete");
        deleteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteBtnMouseClicked(evt);
            }
        });

        HomeBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        HomeBtn.setText("Home");
        HomeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(HomeBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(62, 62, 62)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(busPlateTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                    .addComponent(driverTxt)
                    .addComponent(driverNmbrTxt))
                .addGap(115, 115, 115)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteBtn)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(editBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(addBtn, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addGap(50, 50, 50))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(busPlateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(driverTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HomeBtn)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(addBtn)
                        .addGap(18, 18, 18)
                        .addComponent(editBtn)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(driverNmbrTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteBtn)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        busTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        busTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                busTblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(busTbl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(414, 414, 414)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    String dbUrl = "jdbc:postgresql://localhost:5432/kindergarten_management_db";
    String username = "postgres";
    String password = "8585";
    
    Connection con = null;
    Statement st = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
//    int busId = 0;
    
    private void Clear() {
        busPlateTxt.setText("");
        driverTxt.setText("");
        driverNmbrTxt.setText("");
    }
    
    private void DisplayBuses(){
        try {
            con = DriverManager.getConnection(dbUrl, username, password);
            String sql = "select * from buses";
            st = con.createStatement();
            rs = st.executeQuery(sql);
            busTbl.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void busPlateTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busPlateTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_busPlateTxtActionPerformed

    private void driverNmbrTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_driverNmbrTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_driverNmbrTxtActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
       
        if (busPlateTxt.getText().isEmpty() || driverTxt.getText().isEmpty() || driverNmbrTxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Incomplete information");
        } else if (!busPlateTxt.getText().matches("[A-Z]{3}\\s+\\d{3}\\s+[A-Z]{1}")) {
            JOptionPane.showMessageDialog(this, "Bus plate should be in the format 'RAD 705 R'");
        } else if (driverNmbrTxt.getText().length() != 10) {
            JOptionPane.showMessageDialog(this, "Phone number should be 10 characters");
        }else{
            try {
                con = DriverManager.getConnection(dbUrl, username, password);
                
                // Check if Passenger_id already exists
                String checkBusPlateQuery = "SELECT * FROM buses WHERE bus_plate=?";
                PreparedStatement checkBusPlateStatement = con.prepareStatement(checkBusPlateQuery);
                checkBusPlateStatement.setString(1, busPlateTxt.getText());
                ResultSet existingbusPlate = checkBusPlateStatement.executeQuery();

                if (existingbusPlate.next()) {
                    JOptionPane.showMessageDialog(this, "The bus already exist.");
                    return; // Stop further processing
                }

                // If Passenger_id does not exist, proceed with the insertion
                
                String sql = "insert into buses(bus_plate,driver_name,driver_number) values(?,?,?)";
                PreparedStatement Add = con.prepareCall(sql);
//                Add.setInt(1, busId);
                Add.setString(1, busPlateTxt.getText());
                Add.setString(2, driverTxt.getText());
                Add.setString(3, driverNmbrTxt.getText());
                int rowsAffected = Add.executeUpdate();
                con.close();
                DisplayBuses();
                Clear();
                if (rowsAffected >= 1) {
                    JOptionPane.showMessageDialog(this, "bus Saved Successfully !!!");
                } else {
                    JOptionPane.showMessageDialog(this, "bus Not Saved !!!");
                }
                
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Server Error !!!");
            }
        }

    }//GEN-LAST:event_addBtnActionPerformed

    private void HomeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeBtnActionPerformed

        new Main().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HomeBtnActionPerformed

    private void editBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editBtnMouseClicked
       
      if (Key == 0) {
        JOptionPane.showMessageDialog(this, "Select a bus to update");
    } else {
        try {
            con = DriverManager.getConnection(dbUrl, username, password);
            String sql = "UPDATE buses SET bus_plate=?, driver_name=?, driver_number=? WHERE bus_id=?";
            PreparedStatement update = con.prepareStatement(sql);
            update.setString(1, busPlateTxt.getText());
            update.setString(2, driverTxt.getText());
            update.setString(3, driverNmbrTxt.getText());
            update.setInt(4, Key); // Assuming Key is the bus_id
            int rowsAffected = update.executeUpdate();
            con.close();
            DisplayBuses();
            Clear();
            if (rowsAffected >= 1) {
                JOptionPane.showMessageDialog(this, "Bus updated successfully");
            } else {
                JOptionPane.showMessageDialog(this, "Bus not updated");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Server error");
        }
    }
    }//GEN-LAST:event_editBtnMouseClicked

    int Key = 0;
    private void busTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_busTblMouseClicked
                                                    
        DefaultTableModel model = (DefaultTableModel)busTbl.getModel();
        busTbl.setModel(model);
        
        // Set the table non-editable
        busTbl.setCellSelectionEnabled(false);
        busTbl.setFocusable(false);
        
        int Index = busTbl.getSelectedRow();
        
        Key = Integer.valueOf(model.getValueAt(Index, 0).toString());
         
        busPlateTxt.setText(model.getValueAt(Index, 1).toString());
        driverTxt.setText(model.getValueAt(Index, 2).toString());
        driverNmbrTxt.setText(model.getValueAt(Index, 3).toString());
    }//GEN-LAST:event_busTblMouseClicked

//    String keys = "";
    private void deleteBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtnMouseClicked
        
        System.out.println("Key is "+Key);
        if(Key == 0){
            JOptionPane.showMessageDialog(this, "Select the bus to delete ");
        }else {
            try {
                con = DriverManager.getConnection(dbUrl, username, password);
                String sql = "DELETE FROM buses WHERE bus_id=?";
                PreparedStatement Del = con.prepareStatement(sql);
                Del.setInt(1, Key);
                int rowsAffected = Del.executeUpdate();
                con.close();
                DisplayBuses();
                Clear();
                if (rowsAffected >= 1) {
                    JOptionPane.showMessageDialog(this, "bus deleted Successfully !!!");
                } else {
                    JOptionPane.showMessageDialog(this, "bus Not Deleted !!!");
                }
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Server error !!!");
            }
        }
    }//GEN-LAST:event_deleteBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Buses().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HomeBtn;
    private javax.swing.JButton addBtn;
    private javax.swing.JTextField busPlateTxt;
    private javax.swing.JTable busTbl;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField driverNmbrTxt;
    private javax.swing.JTextField driverTxt;
    private javax.swing.JButton editBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
